Update timecard to use group permissions for balance-calculator consumer
UKHomeOffice/callisto-timecard-restapi pull request #95
Opened 2023-03-15 11:00 UTC by JWeston-HO

2023-03-15 14:07 UTC, joannafawl commented on helm/kafka/scripts/create-topic.sh
> +            if [ -n "$commandd_args" ]
Is this a typo?

2023-03-15 15:56 UTC, JWeston-HO commented on helm/kafka/scripts/create-topic.sh
> +            if [ -n "$commandd_args" ]
Yes it is. Updated

2023-03-15 16:42 UTC, joannafawl submitted a review, later dismissed

2023-03-16 12:36 UTC, stephenkaye-ho requested changes

2023-03-16 12:36 UTC, stephenkaye-ho commented on helm/kafka/scripts/create-topic.sh
>      # form the output with the principals. Then use sed to strip out everything
After comparing this diff to https://github.com/UKHomeOffice/callisto-localdev/commit/a4ec3c2444b28d81c1d621fce81f9070b1a41a1b#diff-c884395578b83214809e2fbf5b807ae20b65760f636ec7119a9801315b3f44a2
Lines 13&14 shouldn't be needed

2023-03-16 16:19 UTC, stephenkaye-ho approved these changes

2023-03-16 16:21 UTC, joannafawl approved these changes

2023-03-16 16:21 UTC, merged